from django.urls import path

urlpatterns = [
    path("login/", name="login"),
    path("register/", name="register"),
    path("forgot_pass/", name="forgot_pass"),
    path("verify_otp/", name="verify_otp"),
    path("change_pass/", name="change_pass"),
    path("create_blog/", name="create_blog"),
    path("get_blog/<int:pk>/", name="get_blog"),
    path("get_all_blog", name="get_all_blog"),
    path("get_blog/<str:cat>/", name="get_blog"),
    path("update_blog/<int:pk>/", name="update_blog"),
    path("delete_blog/<int:pk>/", name="delete_blog"),
    path("publish_blog/", name="publish_blog"),
    path("share_blog/", name="share_blog"),
    path("subscribe/", name="subscribe"),
    path("unsubscribe/", name="unsubscribe"),
    path("contact/", name="contact"),
    path("comments/", name="comments"),
    path("get_comments/", name="get_comments"),
    path("delete_comments/<int:pk>/", name="delete_comments"),
    path("review/", name="review"),
    path("get_review/", name="get_review"),
    path("reply/", name="reply"),
    path("get_reply/", name="get_reply"),
    path("delete_reply/<int:pk>/", name="delete_reply"),
    path("search_blog/<str:name>/", name="search_blog"),
]